name: cicd

on:
  push:
    tags:
      - "*"
      
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create-version
      id: create-version
      run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
    - name: show-version
      run: echo "Version to build -> ${{ steps.create-version.outputs.version }}"
    outputs:
      version: ${{ steps.create-version.outputs.version }}
  
  build-and-push:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v3 
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2  
    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}   
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./Dockerfile
        tags: docker.io/brianwolf94/python3-flask:${{ needs.get-version.outputs.version }} 
        platforms: linux/amd64
        build-args: ARG_VERSION=${{ needs.get-version.outputs.version }}
    - name: Build and push latest
      id: docker_build_latest
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./Dockerfile
        tags: docker.io/brianwolf94/python3-flask:latest
        platforms: linux/amd64
        build-args: ARG_VERSION=latest
    outputs:
      version: ${{ needs.get-version.outputs.version }}
  
